services:
  gitlab:
    image: gitlab/gitlab-ce:18.9.3-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.281018.xyz'
    ports:
     - '80:80'
       # - '443:443'
     - '22:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.281018.xyz'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_https'] = true
        gitlab_rails['gitlab_host'] = 'gitlab.281018.xyz'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
