services:
  timescaledb:
    image: timescale/timescaledb:2.25.2-pg18
    container_name: timescaledb
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password123
      TZ: Asia/Shanghai
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  timescaledb-data:
    name: timescaledb-data
