services:
  mongo:
    image: mongo:8.0.19-noble
    container_name: mongo
    restart: unless-stopped
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      TZ: Asia/Shanghai
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://root:password123@127.0.0.1:27017/admin",
          "--eval",
          "db.adminCommand({ ping: 1 }).ok"
        ]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  mongo-data:
    name: mongo-data
